name: You can't hack me twice, can you?
on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: One
        run: echo $FLAG
        env:
          FLAG: ${{ secrets.FLAG }}
      - name: Two
        run: |
          echo "Even with this obvious injection, I bet you won't be able to print the FLAG..."
          ${{ github.event.issue.title }}
          